chore: añadir pruebas para verificar shell

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -137,6 +137,12 @@ jobs:
     runs-on: self-hosted
     steps:
       - uses: actions/checkout@v4
+      - name: Debug shells
+        run: |
+          echo "Default shell = %COMSPEC%"
+          where bash   || echo "bash NOT found"
+          where pwsh   || echo "pwsh NOT found"
+          where powershell || echo "powershell NOT found"
 
       - name: Deploy to local K8s
         shell: powershell
